apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-component
  title: Terraform Component Template
  description: Create a new Terraform Component configuration
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Basic Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Name of the Terraform Component (lowercase, no spaces)
          default: "tf-workspaces"
          pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
          minLength: 1
          maxLength: 63
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the Terraform Component
          default: "A collection of Terraform workspaces managed via Backstage"
        owner:
          title: Owner
          type: string
          default: "platform-team"
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    # ... rest of your template configuration ...
