apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-component
  title: Terraform Component Template
  description: Create a new Terraform Component configuration
  annotations:
    github.com/project-slug: navneet-bairwal/learn-terraform-run-triggers-network
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Basic Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Name of the Terraform Component
          default: "TF-Workspaces"
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the Terraform Component
          default: "A collection of Terraform workspaces managed via Backstage"
        owner:
          title: Owner
          type: string
          default: "platform-team"
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    - title: Repository Configuration
      properties:
        repoUrl:
          title: Repository URL
          type: string
          default: "github.com?repo=learn-terraform-run-triggers-network&owner=navneet-bairwal"
        branchName:
          title: Branch Name
          type: string
          description: Name of the branch to create
          default: 'add-tf-component'
        targetPath:
          title: Target Path
          type: string
          description: Path in the repository to create the component
          default: "."

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          destination:
            owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
            repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branchName }}
        title: 'Add Terraform Component ${{ parameters.name }}'
        description: |
          This PR adds a new Terraform Component configuration.
          
          - Name: ${{ parameters.name }}
          - Description: ${{ parameters.description }}
          - Owner: ${{ parameters.owner }}
          
          Please review the configuration and merge if everything looks correct.
        sourcePath: '.'
        targetPath: ${{ parameters.targetPath }}

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: ${{ steps.publish.output.remoteUrl }}/blob/master/tf-catalog-info.yaml
        optional: true

  output:
    links:
      - title: Pull Request
        icon: github
        url: ${{ steps.publish.output.remoteUrl }}
